#!/bin/bash

set -e

DOCKER_TARGET=chriz2600
IMAGE_NAME=quartus-lite
IMAGE_TAG=18.1
IMAGE_TAG_EXACT=18.1.1

docker build -t ${DOCKER_TARGET}/${IMAGE_NAME}:${IMAGE_TAG} .
docker tag ${DOCKER_TARGET}/${IMAGE_NAME}:${IMAGE_TAG} ${DOCKER_TARGET}/${IMAGE_NAME}:latest
docker tag ${DOCKER_TARGET}/${IMAGE_NAME}:${IMAGE_TAG} ${DOCKER_TARGET}/${IMAGE_NAME}:${IMAGE_TAG_EXACT}

read -n1 -p "Do you want to push the image to the registry now [yN]? " answer
if [[ "${answer:-n}" == "y" ]]
then
    docker push ${DOCKER_TARGET}/${IMAGE_NAME}:${IMAGE_TAG}
    docker push ${DOCKER_TARGET}/${IMAGE_NAME}:latest
    docker push ${DOCKER_TARGET}/${IMAGE_NAME}:${IMAGE_TAG_EXACT}
fi
